title: Blog for Laurentius
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs@v0.5.2

#theme: just-the-docs

url: https://LaurentiusCanadensis.github.io

aux_links:
  Template Repository: https://github.com/LaurentiusCanadensis/laurentiuscanadensis.github.io/

plugins:
  - jekyll-default-layout


  
